### ISSUE TITLE
Homoglyph#search() is not symmetric for 1 & i characters

### ISSUE THREAD

**Issue by peshrus** [codebox/homoglyph#12]
# Expectation
`homoglyph.search("1", "i")` and `homoglyph.search("i", "1")` return 1 result because they are homoglyphs.

# Reality
`homoglyph.search("1", "i")` returns 1 search result `'1' at position 0 matches 'i'`.
**`homoglyph.search("i", "1")` returns nothing.**

As you can see in the test below the same expectation works well for `O` & `0`.

# Test
```kotlin
import io.kotest.assertions.assertSoftly
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.collections.shouldHaveSize
import net.codebox.homoglyph.HomoglyphBuilder

class HomoglyphTest : DescribeSpec({
    describe("Homoglyph.search() is symmetric") {
        it("for characters 1 & i") {
            // Arrange
            val homoglyph = HomoglyphBuilder.build()

            // Act
            val actual1 = homoglyph.search("1", "i")
            val actual2 = homoglyph.search("i", "1")

            // Assert
            assertSoftly {
                actual1 shouldHaveSize 1
                actual2 shouldHaveSize 1
            }
        }

        it("for characters 0 & O") {
            // Arrange
            val homoglyph = HomoglyphBuilder.build()

            // Act
            val actual1 = homoglyph.search("0", "O")
            val actual2 = homoglyph.search("O", "0")

            // Assert
            assertSoftly {
                actual1 shouldHaveSize 1
                actual2 shouldHaveSize 1
            }
        }
    }
})
```

**Comment by codebox** [comment]
I'm not able to replicate this problem after adding the 'i' -> '1' mapping to confusables_extras.txt and regenerating the raw_data directory, I see one match for all the test cases above. 

You might however see this issue if you added this test into the 'HomoglyphLogicTest' class which does not use a full set of homoglyphs but rather a small set of mocked data that does not include the lower case letter 'i'. In this case the asymmetry would be caused by the fact that when the 'targetWord' parameter of the Homoglyph.search method has it characters checked for homoglyphs each character is converted to both upper and lower case and each is checked. Because the mock homoglyph data in the test includes capital 'I', when the small 'i' was converted to uppercase it matched the number '1', but when the values are reversed we are still comparing 'i' to '1' which is not a match according to the mocked data.
