### ISSUE TITLE
Coordination with Python libraries?

### ISSUE THREAD

**Issue by DonaldTsang** [codebox/homoglyph#8]
There are other libraries like https://github.com/life4/homoglyphs that does something similar, but there is a lack of standards for what constitutes "homoglyph".

Similar character tables for reference: https://github.com/life4/homoglyphs/tree/master/homoglyphs

**Comment by codebox** [comment]
Closing because I don't see this as an issue I can solve. Whether something is a homoglyph or not is always going to be somewhat subjective. The list that this project uses is based on the Unicode Consortium's [list of 'confusable characters'](https://www.unicode.org/Public/security/8.0.0/confusables.txt) which is probably as close to a standard as we are going to get.
